project:
  type: website
  output-dir: docs


website:
  title: "Matt Braaksma"
  favicon: "assets/img/favicon_io/favicon.ico"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: "CV"
      - href: research.qmd
        text: "Research"
      - href: teaching.qmd
        text: "Teaching"
      - href: presentations.qmd
        text: "Presentations"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



