project:
  type: website
  output-dir: docs


website:
  title: "Matt Braaksma"
  favicon: "assets/img/favicon_io/favicon.ico"
  navbar:
    right:
      - href: index.html
        text: Home
      - href: cv.html
        text: "CV"
      - href: research.html
        text: "Research"
      - href: teaching.html
        text: "Teaching"
      - href: presentations.html
        text: "Presentations"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



