project:
  type: website
  output-dir: docs


website:
  title: "Matt Braaksma"
  favicon: "img/favicon_io/favicon.ico"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: "CV"
      - href: presentations.qmd
        text: "Presentations"
      # - href: publications
      #   text: "Publications"
      # - href: teaching
      #   text: "Teaching"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



