---
title: "Research"
---

## Working Papers

Dave, Dhaval, Yang Liang, Catherine Maclean, Joseph Sabia, and Matthew Braaksma. "Can Anti-Vaping Policies Curb Drinking Externalities? Evidence from E-Cigarette Taxation and Traffic Fatalities". No. w30670. *National Bureau of Economic Research*, 2022.

## Publications

McWay, Ryan, and Matthew Braaksma. 2025. "The Political Consequences of Resource Scarcity: Targeted Spending in a Water-Stressed Democracy. A Replication Study of Mahadevan and Shenoy (Journal of Public Economics, 2023)". *World Development Perspectives* 39: 100707. [https://doi.org/10.1016/j.wdp.2025.100707](https://doi.org/10.1016/j.wdp.2025.100707)

## Conference Presentations

"A Framework for Measuring African Ecosystem Services Impacts from Land-Related Policies". 28th Annual Conference on Global Economic Analysis: "Accelerating Economic Transformation, Resilience, Diversification, and Job Creation". Global Trade Analysis Project (GTAP). Kigali, Rwanda, June 25--27, 2025.